### ISSUE TITLE
01_original.py not running

### ISSUE THREAD

**Issue by dakshanand** [Shmuma/ptan#7]
I tried to run the 1st code under dqn_speedup by running the command python 01_original.py and get the following error.
`Traceback (most recent call last):
  File "01_original.py", line 32, in <module>
    exp_source = ptan.experience.ExperienceSourceFirstLast(env, agent, gamma=params['gamma'], steps_count=1)
  File "/home/daksh/anaconda2/envs/torch/lib/python2.7/site-packages/ptan/experience.py", line 168, in __init__
    super(ExperienceSourceFirstLast, self).__init__(env, agent, steps_count+1, steps_delta, vectorized=vectorized)
TypeError: super() argument 1 must be type, not classobj
`
Please look into it and let me know.

**Comment by dakshanand** [comment]
I then tried to use the exact same versions of python modules as given in your requirements.txt and then get this error - 
`Traceback (most recent call last):
  File "01_original.py", line 23, in <module>
    env = ptan.common.wrappers.wrap_dqn(env)
  File "/home/daksh/anaconda2/lib/python2.7/site-packages/ptan/common/wrappers.py", line 235, in wrap_dqn
    env = ProcessFrame84(env)
  File "/home/daksh/anaconda2/lib/python2.7/site-packages/ptan/common/wrappers.py", line 133, in __init__
    self.observation_space = spaces.Box(low=0, high=255, shape=(84, 84, 1), dtype=np.uint8)
TypeError: __init__() got an unexpected keyword argument 'dtype'
`
